simplesocial/accounts/urls.py
from django.urls import path , include
from django.contrib.auth import views as auth_views  # django has builtin login view and logout view so we dont have to create it

from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/' , auth_views.LoginView.as_view(template_name = 'accounts/login.html') , name='login') ,
    path('logout/' , auth_views.LogoutView.as_view() , name='logout') , # it will take you to home page after you logout
    path('signup/' , views.SignUp.as_view() , name='signup') ,
    path('password/' , views.change_pass , name='change_password') ,

    # for password reset... can read about reset password here - >  https://simpleisbetterthancomplex.com/tutorial/2016/09/19/how-to-create-password-reset-view.html
#    path('' , include('django.contrib.auth.urls') ) ,

    # OR see in that link
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name = 'accounts/password_reset_form.html' , subject_template_name = 'accounts/password_reset_subject.txt' , email_template_name = 'accounts/password_reset_email.html') , name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name = 'accounts/password_reset_done.html') , name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name = 'accounts/password_reset_confirm.html') , name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name = 'accounts/password_reset_complete.html') , name='password_reset_complete'),

#    path('' , include('django.contrib.auth.urls') ) ,

]

simplesocial/posts/urls.py
from django.urls import path
from posts import views

app_name = 'posts'
urlpatterns = [
    path('' , views.PostList.as_view() , name='all') ,
    path('new/' , views.CreatePost.as_view() , name='create') ,
    path('by/<str:username>/' , views.UserPosts.as_view() , name='for_user') ,
    path('by/<str:username>/<slug:pk>/' , views.PostDetail.as_view() , name='single') ,
    path('delete/<slug:pk>/' , views.DeletePost.as_view() , name='delete'),

]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views # grab views from current directory

urlpatterns = [
    path('' , views.HomePage.as_view() , name='home'),
    path('accounts/' , include('accounts.urls' , namespace='accounts')) , #find what namespace is for?
    path('accounts/' , include('django.contrib.auth.urls') ) , # connects everything django has related to authorization to accounts app
    # no need to register any models in admin of accounts as using django's builtin user models.. so no need to register anythign in accounts admin
    path('test/' , views.TestPage.as_view() , name='test'),  # for loggin in page
    path('thanks/' , views.ThanksPage.as_view() , name='thanks'), # logging out page

    path('posts/' , include('posts.urls' , namespace='posts') ) ,
    path('groups/' , include('groups.urls' , namespace='groups') ) , 

    path('admin/', admin.site.urls),
]

simplesocial/accounts/models.py
from django.db import models
from django.contrib import auth
# Create your models here.

class User(auth.models.User , auth.models.PermissionsMixin): # all work is done by django..

    def __str__(self):
        return '@{}'.format(self.username) # username comes with class User

simplesocial/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):

    class Meta():
        fields = ('username' , 'email' , 'password1' , 'password2')
        model = get_user_model()

    def __init__(self , *args , **kwargs):
        super().__init__(*args , **kwargs)
        self.fields['username'].label = 'Display Name' # setting label here like did in html files... it's mandatory    
        self.fields['email'].label = 'Email Address'

simplesocial/accounts/views.py
from django.shortcuts import render , get_object_or_404 , redirect
from django.views.generic import (TemplateView , ListView , DetailView , CreateView , UpdateView , DeleteView)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy

#for password change
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash #important for changin password
from django.contrib.auth.forms import PasswordChangeForm #built in form

from .models import User
from . import forms
# Create your views here.
class SignUp(CreateView):
    template_name = 'accounts/signup.html'
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('login') # once soeomeone has signed up.. take then to login page


def change_pass(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user , request.POST) #so that form gets the authenticated user


        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request , user) # importatnt cos else after saving form.. user's auth session will be invalidated and he will have to login again
            messages.success(request , 'Your Password was succesfullu updated.')
            return redirect('test')

        else:
            messages.error(request , 'Form not Valid!')

    else:
        form = PasswordChangeForm(request.user)

    return render(request , 'accounts/change_password.html' , {'form' : form} )

simplesocial/accounts/templates/accounts/change_password.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}

<div class="container">
  <h1>Change Password</h1>
  <form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-default" value="Change Password">

  </form>

</div>

{% endblock %}

simplesocial/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}

  <div class="container">
    <h1>Log In</h1>
    <form method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-default" value="Log In">
      <a href="{% url 'accounts:password_reset' %}"> Forgot Password? </a>

    </form>

  </div>

{% endblock %}

simplesocial/accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
  <p>
    Your password has been set. You may go ahead and <a href="{% url 'accounts:login' %}"> Login </a> now.
  </p>
{% endblock %}

simplesocial/accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}

  {% if validlink %}
    <h3>Change password</h3>

    <form method="POST">

      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-default" value="Submit">

    </form>

  {% else %}

    <p>
      The password reset link was invalid, possibly because it has already been used.
      Please request a new password reset.
    </p>

  {% endif %}

{% endblock %}

simplesocial/accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}

{% block content %}
  <p>
    We've emailed you instructions for setting your password, if an account exists with the email you entered.
    You should receive them shortly.
  </p>
  <p>
    If you don't receive an email, please make sure you've entered the address you registered with,
    and check your spam folder.
  </p>
{% endblock %}

simplesocial/accounts/templates/accounts/password_reset_email.html
<!-- {% autoescape off %}
To initiate the password reset process for your {{ user.get_username }} TestSite Account,
click the link below:

{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
The TestSite Team
{% endautoescape %}
<!-- {% load i18n %} -->

{% load i18n %}
{% autoescape off %}

{% blocktrans %}
  You're receiving this email because you requested a password reset for your user account at {{ site_name }}.
{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}

  {{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

{% endblock %}

{% trans "Your username, in case you've forgotten:" %}

  {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}

  The {{ site_name }} team

{% endblocktrans %}

{% endautoescape %}

simplesocial/accounts/templates/accounts/password_reset_form.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}

  <h3> Forgot Password </h3>
  <form method="POST">

    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-default" value="Submit">

  </form>

{% endblock %}

simplesocial/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}

  <div class="container">
    <h1>Sign Up</h1>
    <form method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-default" value="Sign Up">

    </form>

  </div>

{% endblock %}