simplesocial/accounts/urls.py
from django.urls import path , include
from django.contrib.auth import views as auth_views  # django has builtin login view and logout view so we dont have to create it

from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/' , auth_views.LoginView.as_view(template_name = 'accounts/login.html') , name='login') ,
    path('logout/' , auth_views.LogoutView.as_view() , name='logout') , # it will take you to home page after you logout
    path('signup/' , views.SignUp.as_view() , name='signup') ,
    path('password/' , views.change_pass , name='change_password') ,

    # for password reset... can read about reset password here - >  https://simpleisbetterthancomplex.com/tutorial/2016/09/19/how-to-create-password-reset-view.html
#    path('' , include('django.contrib.auth.urls') ) ,

    # OR see in that link
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name = 'accounts/password_reset_form.html' , subject_template_name = 'accounts/password_reset_subject.txt' , email_template_name = 'accounts/password_reset_email.html') , name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name = 'accounts/password_reset_done.html') , name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name = 'accounts/password_reset_confirm.html') , name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name = 'accounts/password_reset_complete.html') , name='password_reset_complete'),

#    path('' , include('django.contrib.auth.urls') ) ,

]

simplesocial/posts/urls.py
from django.urls import path
from posts import views

app_name = 'posts'
urlpatterns = [
    path('' , views.PostList.as_view() , name='all') ,
    path('new/' , views.CreatePost.as_view() , name='create') ,
    path('by/<str:username>/' , views.UserPosts.as_view() , name='for_user') ,
    path('by/<str:username>/<slug:pk>/' , views.PostDetail.as_view() , name='single') ,
    path('delete/<slug:pk>/' , views.DeletePost.as_view() , name='delete'),

]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views # grab views from current directory

urlpatterns = [
    path('' , views.HomePage.as_view() , name='home'),
    path('accounts/' , include('accounts.urls' , namespace='accounts')) , #find what namespace is for?
    path('accounts/' , include('django.contrib.auth.urls') ) , # connects everything django has related to authorization to accounts app
    # no need to register any models in admin of accounts as using django's builtin user models.. so no need to register anythign in accounts admin
    path('test/' , views.TestPage.as_view() , name='test'),  # for loggin in page
    path('thanks/' , views.ThanksPage.as_view() , name='thanks'), # logging out page

    path('posts/' , include('posts.urls' , namespace='posts') ) ,
    path('groups/' , include('groups.urls' , namespace='groups') ) , 

    path('admin/', admin.site.urls),
]

simplesocial/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Star Social</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">

  </head>
  <body>

    <nav class="navbar  mynav" role="navigation" id="navbar">
    	<div class="container">
        <a class="navbar-brand mynav" href="{% url 'home' %}"> Star Social </a>

        <ul class="nav navbar-nav navbar-right">

          {% if user.is_authenticated %}
            <li> <a href="{% url 'posts:create' %}"> Post </a> </li>
            <li> <a href="{% url 'groups:all' %}"> Groups </a> </li>
            <li> <a href="{% url 'groups:create' %}"> Create Group </a> </li>
            <li> <a href="{% url 'accounts:change_password' %}"> Change Password </a> </li>
            <li> <a href="{% url 'accounts:logout' %}"> Log Out </a> </li>
          {% else %}
            <li> <a href="{% url 'groups:all' %}">Groups</a> </li>
            <li> <a href="{% url 'accounts:login' %}"> Log In </a> </li>
            <li> <a href="{% url 'accounts:signup' %}"> Sign Up </a> </li>
          {% endif %}

        </ul>
      </div>
    </nav>

    <div class="container mycontent">

      {% block content %}

      {% endblock %}

    </div>

    <canvas id="canvas"></canvas>


  </body>

{# JAVA SCUIPT IS LOADED HERE #}
  <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" >
  </script>



</html>

simplesocial/templates/index.html
{% extends "base.html" %}

{% block content %}

 <h1> Welcome to Star Social! </h1>

{% endblock %}

simplesocial/templates/test.html
{% extends 'base.html' %}

{% block content %}

  <h1>You are now logged in!</h1>

{% endblock %}

simplesocial/templates/thanks.html
{% extends 'base.html' %}

{% block content %}

  <h1>Thanks for visiting, come back soon!</h1>

{% endblock %}