simplesocial/posts/urls.py
from django.urls import path
from posts import views

app_name = 'posts'
urlpatterns = [
    path('' , views.PostList.as_view() , name='all') ,
    path('new/' , views.CreatePost.as_view() , name='create') ,
    path('by/<str:username>/' , views.UserPosts.as_view() , name='for_user') ,
    path('by/<str:username>/<slug:pk>/' , views.PostDetail.as_view() , name='single') ,
    path('delete/<slug:pk>/' , views.DeletePost.as_view() , name='delete'),

]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views # grab views from current directory

urlpatterns = [
    path('' , views.HomePage.as_view() , name='home'),
    path('accounts/' , include('accounts.urls' , namespace='accounts')) , #find what namespace is for?
    path('accounts/' , include('django.contrib.auth.urls') ) , # connects everything django has related to authorization to accounts app
    # no need to register any models in admin of accounts as using django's builtin user models.. so no need to register anythign in accounts admin
    path('test/' , views.TestPage.as_view() , name='test'),  # for loggin in page
    path('thanks/' , views.ThanksPage.as_view() , name='thanks'), # logging out page

    path('posts/' , include('posts.urls' , namespace='posts') ) ,
    path('groups/' , include('groups.urls' , namespace='groups') ) , 

    path('admin/', admin.site.urls),
]

simplesocial/posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings


import misaka # so people can wrtie markdown in their posts
from groups.models import Group
# Create your models here.
from django.contrib.auth import get_user_model
User = get_user_model()

class Post(models.Model):
    user = models.ForeignKey(User , related_name='posts' , on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True) # means date / time will be got automatically as post's created
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group , related_name='posts' , null=True , blank=True , on_delete=models.CASCADE)

    def __str__(self):
        return self.message

    def save(self , *args , **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args , **kwargs)

    def get_absolute_url(self):
        return reverse('posts:single' , kwargs = {'username' : self.user.username , 'pk' : self.pk} )

    class Meta():
        ordering = ['-created_at'] # - so see it in descending order... most recent at top
        unique_together = ['user' , 'message']

simplesocial/posts/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import (TemplateView , ListView , DetailView , CreateView , UpdateView , DeleteView)
from django.http import Http404

from django.contrib import messages

from braces.views import SelectRelatedMixin

from posts.models import Post
from django.contrib.auth import get_user_model
# Create your views here.
User = get_user_model()

class PostList(ListView , SelectRelatedMixin):
    model = Post
    select_related = ('user' , 'group') # from Post model

class UserPosts(ListView):
    model = Post
    template_name = 'posts/user_post_list.html'

    #have to add some methods to make sure this works correctly  when logged in user

    def get_queryset(self): # check if username is qual to get username of who is logged in rn
        try:
            self.post_user = User.objects.prefetch_related('posts').get(username__iexact = self.kwargs.get('username')) # check in doc
            # if goto user posts..for post's user.. grab all posts related to that exact tusername
        except User.DoesNotExist:
            raise Http404

        else:
            return self.post_user.posts.all()


    def get_context_data(self , **kwargs): # grabs post_user and return context dictionary off of that
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context


# Detail View
class PostDetail(DetailView , SelectRelatedMixin):
    model = Post
    select_related = ('user' , 'group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact = self.kwargs.get('username'))


#Create Post

class CreatePost(LoginRequiredMixin , CreateView , SelectRelatedMixin):
    fields = ('message' , 'group')
    model = Post

    def form_valid(self , form): # cehcking form is valid.. acnd connecting post to the user
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save() # to connect actual post to user itself
        return super().form_valid(form)

            # A lot of thing s/ variable comes with generic classes we're not amking them
#Delete Post
class DeletePost(SelectRelatedMixin , LoginRequiredMixin , DeleteView):
    model = Post
    select_related = ('user' , 'group')
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id = self.request.user.id)

    def delete(self , *args , **kwargs): # return message that post was deleted
        messages.success(self.request , 'Post Deleted')
        return super().delete(*args , **kwargs)

simplesocial/posts/templates/posts/_post.html
<!-- Will use it to inject to other post.html files... if ur html page is getting too big / complicated
    we can break that page and inject it
    since injecting so no need to extend
  -->

<div class="post media">
  	<h3>{{ post.message_html|safe }}</h3>
  	<div class="media-body">

      <!-- <strong>{{ post.user.username }}</strong> -->
  		<h5 class="media-heading">

      	<span class="username"><a href="{% url 'posts:for_user' username=post.user.username %}">@{{ post.user.username }}  </a></span>
          <!-- check urls.py.... User Posts list view ka url takes one parameter /<username>  -->
  			<time class="time"><a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{ post.created_at }}  </a></time>
        <!--  post detail  -->
  			{% if post.group %}
  			<span class="group-name">in <a href="{% url 'groups:single' slug=post.group.slug %}">{{ post.group.name }}</a></span>

      	{% endif %}
  		</h5>




  		<div class="media-footer">
  			{% if user.is_authenticated and post.user == user %}   <!-- and not hide_delete %}  -->
<!-- checks if user authenticated and the logged in user which is just user is same as post's user i.e post.user  -->
  				<a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-simple">
  					<span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
  					<span class="text-danger icon-label">Delete</span>
  				</a>

  			{% endif %}

  		</div>
  	</div>
</div>

simplesocial/posts/templates/posts/post_base.html
{% extends 'base.html' %}

{% block content %}

<div class="posts-page">
	<div class="container">
		<div class="row">

			{% block prepost %}
			{% endblock %}

			{% block post_content %}
			{% endblock %}

			{% block post_post%}
			{% endblock %}

		</div>
	</div>
</div>

{% endblock %}

simplesocial/posts/templates/posts/post_confirm_delete.html
{% extends 'posts/post_base.html' %}

{% block post_content %}

  <h3> Are you sure you want to delete this post? </h3>
  <div class="posts">
    {% include 'posts/_post.html' with post=object hide_delete=True %}
    <!--  shows that post  -->
  </div>

  <form  method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger btn-large" value="Confirm Delete">
    <a href="{% url 'posts:single' username=user.username pk=object.pk  %}" class="btn btn-simple btn-large btn-default"> Cancel </a>
  </form>

{% endblock %}

simplesocial/posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}

{% block post_content %}
<div class="col-md-8">
    {% include "posts/_post.html" %}
</div>
{% endblock %}

simplesocial/posts/templates/posts/post_form.html
{% extends 'posts/post_base.html' %}
{% load bootstrap3 %}

{% block post_content %}

  <h3> Create a new Post! </h3>
  <form id='postform' action="{% url 'posts:create' %}"  method="post">
    {% csrf_token %}
    {% bootstrap_form form %}

    <input type="submit" value="Post" class="btn btn-primary btn-large">


  </form>


{% endblock %}

simplesocial/posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}
{% load humanize %}

{% block pre_post_content %}
<div class="col-md-4">
	{% if request.user.is_authenticated %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">Your Groups</h5>
			<ul class="list-unstyled">
				{% for member_group in get_user_groups %}
				<li class="group li-with-bullet">
					<a href="{% url 'groups:single' slug=member_group.group.slug %}">{{ member_group.group.name }}</a>
																			<!--grabbing .group from all usergroups and grabbing .slug of that group  -->
				</li>
				{% endfor %}

			</ul>
		</div>
	</div>
	{% endif %}
	<div class="card card-with-shadow">
		<div class="content">

			<h5 class="title">All groups</h5>
			<ul class="list-unstyled">
				{% for other_group in get_other_groups %}
					<li class="group li-with-bullet"><a href="{% url 'groups:single' slug=other_group.slug %}">{{ other_group.name }}</a></li>
																																	<!-- not calling .group as group itself is in other_group  -->
				{% endfor %}
			</ul>

		</div>
	</div>
</div>

{% endblock %}


{% block post_content %}
<div class="col-md-8">
	{% for post in post_list %}
  {% include "posts/_post.html" %}
	{% endfor %}
</div>
{% endblock %}

simplesocial/posts/templates/posts/user_post_lists.html
{% extends "posts/post_base.html" %}

{% block prepost %}

<div class="col-md-4">
	<h1>@ {{ post_user.username }}</h1> <!-- post_user was created in try of UserPosts view -->
	<p>Post History</p>
	<h2> kahan ha? </h2>
	<h3> come on man</h3>

</div>
{% endblock %}

{% block post_content %}

<div class="col-md-8">

	{% for post in post_list %}
		{% include "posts/_post.html" %}
	{% endfor %}

</div>
{% endblock %}