simplesocial/groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'
urlpatterns = [
    path('' , views.ListGroups.as_view() , name='all') ,
    path('new/' , views.CreateGroup.as_view() , name='create') ,
    path('posts/in/<slug:slug>/' , views.SingleGroup.as_view() , name='single') , #detail view pf group
    path('join/<slug:slug>/' , views.JoinGroup.as_view() , name='join') ,
    path('leave/<slug:slug>/' , views.LeaveGroup.as_view() , name='leave') ,
]

simplesocial/posts/urls.py
from django.urls import path
from posts import views

app_name = 'posts'
urlpatterns = [
    path('' , views.PostList.as_view() , name='all') ,
    path('new/' , views.CreatePost.as_view() , name='create') ,
    path('by/<str:username>/' , views.UserPosts.as_view() , name='for_user') ,
    path('by/<str:username>/<slug:pk>/' , views.PostDetail.as_view() , name='single') ,
    path('delete/<slug:pk>/' , views.DeletePost.as_view() , name='delete'),

]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views # grab views from current directory

urlpatterns = [
    path('' , views.HomePage.as_view() , name='home'),
    path('accounts/' , include('accounts.urls' , namespace='accounts')) , #find what namespace is for?
    path('accounts/' , include('django.contrib.auth.urls') ) , # connects everything django has related to authorization to accounts app
    # no need to register any models in admin of accounts as using django's builtin user models.. so no need to register anythign in accounts admin
    path('test/' , views.TestPage.as_view() , name='test'),  # for loggin in page
    path('thanks/' , views.ThanksPage.as_view() , name='thanks'), # logging out page

    path('posts/' , include('posts.urls' , namespace='posts') ) ,
    path('groups/' , include('groups.urls' , namespace='groups') ) , 

    path('admin/', admin.site.urls),
]

simplesocial/groups/models.py
from django.db import models
from django.utils.text import slugify # converts string to lowercase... removes alphanum characters like space and puts _ underscore
# if u have string that has spaces in it and u want to use it as aprt of url slugify will arrange it
from django.urls import reverse
import misaka # can put down links or markdown text using it... pip install misaka
from django.contrib.auth import get_user_model #returns user model that is active in this project
User = get_user_model()

from django import template
register = template.Library() # this is how we can use custom template tags
# Create your models here.

class Group(models.Model):
    name = models.CharField(max_length=256 , unique=True) # unique cos dont want groups to have same names
    slug = models.SlugField(allow_unicode=True , unique=True) # unique so all url codes are diff for diff groups
    description = models.TextField(blank=True , default='') #  desc can be blank so black = true.. default value will be ''
    description_html = models.TextField(editable=False , default='' , blank=True) # is not editable.. can be blank
    members = models.ManyToManyField(User , through='GroupMember') # through GroupMember class

    def __str__(self):
        return self.name

    def save(self , *args , **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description) # in case we have markdown in desc we can call it by misaka
        super().save(*args , **kwargs)

    def get_absolute_url(self):
        return reverse('groups:single' , kwargs={"slug" : self.slug} )

    class Meta():
        ordering = ['name']

class GroupMember(models.Model):
    group = models.ForeignKey(Group , related_name='memberships' , on_delete=models.CASCADE)
    user = models.ForeignKey(User , related_name='user_groups' , on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta():
        unique_together = ('group' , 'user') #will explain later


# Group Member class connects to the group and user which is activated
# Group Class name , description , slug , description_html that we will use with misaka to get some markdwon text...
# and finally we have which has ManyToManyField which means all the members which is connected to that Group

simplesocial/groups/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin , PermissionRequiredMixin # checks that current user has all permission
from django.urls import reverse
from django.views.generic import (TemplateView , ListView , DetailView , CreateView , UpdateView , DeleteView
                                    , RedirectView)
from django.contrib import messages

from django.shortcuts import get_object_or_404
from groups.models import Group , GroupMember
from . import models
# Create your views here.

class CreateGroup(CreateView , LoginRequiredMixin):
    fields = ('name' , 'description')
    model = Group


class SingleGroup(DetailView):
    model = Group

class ListGroups(ListView):
    model = Group


# JOIN AND LEAVE GROUPS
# DESCRIPTIOM FOR BOTH GROUPS IS IN TEXT FILE IN FOLDER OF VIDEOS... DIDNT FIND ANY DIFF IN BOTH YET BUT HTAT CODE NOT WORKS

class JoinGroup(LoginRequiredMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get("slug"))

        try:
            GroupMember.objects.create(user=self.request.user,group=group)

        except IntegrityError:
            messages.warning(self.request,("Warning, already a member of {}".format(group.name)))

        else:
            messages.success(self.request,"You are now a member of the {} group.".format(group.name))

        return super().get(request, *args, **kwargs)


class LeaveGroup(LoginRequiredMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):

        try:

            membership = models.GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get("slug")
            ).get()

        except models.GroupMember.DoesNotExist:
            messages.warning(
                self.request,
                "You can't leave this group because you aren't in it."
            )
        else:
            membership.delete()
            messages.success(
                self.request,
                "You have successfully left this group."
            )
        return super().get(request, *args, **kwargs)

simplesocial/groups/templates/groups/group_base.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
  <div class="row">

    {% block pregroup %} {% endblock %}
    {% block group_content %} {% endblock %}
    {% block postgroup %} {% endblock %}

  </div>

</div>

{% endblock %}

simplesocial/groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}

<!-- Everything we want to occur before group name  -->
{% block pregroup %}

  <h1> {{ group.name }} </h1> <!-- context dictionary passed by Detail view... lowercase (model) -->
  <h2> Members :  {{ group.members.count }} </h2>

  <!-- if ur a member and ur logged in.. we have to show a join or leave button   -->
  <div class="content">
    {% if user in group.members.all %} <!-- if this user in inside list of members -->

      <a href="{% url 'groups:leave' slug=group.slug %}"
      class="btn btn-lg btn-fill btn-warning"> <span class='glyphicon glyphicon-remove-circle'> </span> Leave </a>

    {% else %}

    <a href="{% url 'groups:join' slug=group.slug %}"
    class="btn btn-lg btn-fill btn-warning"> <span class='glyphicon glyphicon-ok-circle'> </span> Join Group </a>

    {% endif %}


  </div>

{% endblock %}

<!-- After pregroup   -->

{% block group_content %}

  <div class="col-md-8">
    {% if group.posts.count == 0 %}  <!--  posts was related name of foreign key inside Post model of group  -->
      <h2>No posts in this group yet!</h2>

    {% else %}
      {% for post in group.posts.all %}
        {% include "posts/_post.html" %}

      {% endfor %}

    {% endif %}

  </div>

{% endblock %}

simplesocial/groups/templates/groups/group_form.html
{% extends 'groups/group_base.html' %}
{% load bootstrap3 %}

{% block group_content %}

  <h4>Create a new group!</h4>
  <form action="{% url 'groups:create' %}" method="POST" id='groupForm'> <!-- id for css shyd -->

    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary btn-large" value="Create">

  </form>

{% endblock %}

simplesocial/groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

{% block pregroup %}

  <div class="col-md-4">
    <div class="content">
      {% if user.is_authenticated %}
        <h2> Welcome Back! <a href="{% url 'posts:for_user' username=user.username  %}"> @{{ user.username }} </a> </h2>
            <!-- Click on name.. wil take to all ur posts   -->

      {% endif %}

      <h2> Groups </h2>
      <p> Welcome to Groups page! </p>

    </div>

    {% if user.is_authenticated %}
      <a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning">
        <span class="glyphicon glyphicon-plus-sign"> Create Group </span> </a>

    {% endif %}

  </div>

{% endblock %}

<!--  after pregroup -->

{% block group_content %}

  <div class="col-md-8">
    <div class="list-group">

      {% for group in object_list %}
        <a href="{% url 'groups:single' slug=group.slug %}" class="list-group-item">
            <h3 class="title list-group-item-heading"> {{group.name}} </h3>
            <div class="list-group-item-text container-fluid">
              {{ group.description|safe }}

              <div class="row">
                <div class="col-md-4">
                  <span class="badge"> {{group.members.count}} </span>
                  member{{ group.members.count|pluralize }}
                </div>

                <div class="col-md-4">
                  <span class="badge">{{ group.posts.count }}</span> post{{ group.posts.count|pluralize }}
                </div>

              </div>
            </div>
        </a>

      {% endfor %}

    </div>
  </div>

{% endblock %}